USE DATABASE YELP_BI;

CREATE OR REPLACE TABLE RAW.YELP_REVIEWS (
    review_record VARIANT
);

CREATE OR REPLACE TABLE RAW.YELP_BUSINESSES (
    business_record VARIANT
);

CREATE OR REPLACE FILE FORMAT RAW.YELP_JSON_FORMAT
    TYPE = JSON;
