USE DATABASE YELP_BI;

-- Replace the placeholders before running.
-- Use a Snowflake storage integration instead of placing AWS keys in SQL.

CREATE OR REPLACE STAGE RAW.YELP_S3_STAGE
    URL = 's3://<YOUR_BUCKET_NAME>/'
    STORAGE_INTEGRATION = <YOUR_SNOWFLAKE_STORAGE_INTEGRATION>
    FILE_FORMAT = RAW.YELP_JSON_FORMAT;

COPY INTO RAW.YELP_REVIEWS
FROM @RAW.YELP_S3_STAGE/Yelp_reviews/
FILE_FORMAT = (FORMAT_NAME = RAW.YELP_JSON_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.YELP_BUSINESSES
FROM @RAW.YELP_S3_STAGE/Yelp_business/
FILE_FORMAT = (FORMAT_NAME = RAW.YELP_JSON_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS raw_review_rows
FROM RAW.YELP_REVIEWS;

SELECT COUNT(*) AS raw_business_rows
FROM RAW.YELP_BUSINESSES;
